Intersection search
cgxeiji/scholar pull request #6
Opened 2021-03-12 22:11 UTC by amackcrane

Existing search behavior (used in fetch, open, edit etc.) is to accept multiple search terms from the CLI, but join them together before passing to the search functions, meaning that search is always for a verbatim string.

These changes preserve that behavior for quoted multiword search terms. However for unquoted search terms, we now pass them through as an array, search on each separately, and return the intersection of entries matching each term.

Let me know if this is to your liking!

2021-03-13 00:01 UTC, cgxeiji commented
This looks like a nice enhancement!

What is the impact on performance? Is it still an instant search?

2021-03-13 00:12 UTC, cgxeiji requested changes
Fix some styling.

2021-03-13 00:12 UTC, cgxeiji commented on cmd/gui.go
> +			search_string := strings.Join(search, " ")
Change the variable name `search_string` to mixedCaps or simpler word (maybe just `s`) to keep with Go's naming conventions (https://golang.org/doc/effective_go#names).

2021-03-13 00:21 UTC, amackcrane commented
> This looks like a nice enhancement!
> 
> What is the impact on performance? Is it still an instant search?

Ahh, I started wondering that as I wrote this. Search is not instant for me, I'll test soon to see if this is why

2021-03-13 20:40 UTC, amackcrane commented
Ok, I timed some tests fetching simple and compound queries on a ~400-entry library, including queries that matched many, one, and zero results, comparing compilations of this branch vs. main.

I couldn't discern any significant difference due to this change, which made sense when I remembered that searcher() is being called on individual entries in a short-circuiting boolean expression, so the number of invocations is sublinear in query length.

What I found more interesting is the way that the first in a series of fetch commands often takes 3-4s, while subsequent ones take around .1s, irrespective of query length or relatedness. Out of curiosity, do you know what causes that? Is that golang doing some caching?

2021-03-13 20:41 UTC, amackcrane commented on cmd/gui.go
> +			search_string := strings.Join(search, " ")
fixed thanks!

2021-03-15 06:03 UTC, cgxeiji approved these changes

2021-03-15 06:05 UTC, merged

2021-03-15 06:05 UTC, cgxeiji commented
Thank you for taking the time to check the performance. I also tested on my machine and seems good to go.

> What I found more interesting is the way that the first in a series of fetch commands often takes 3-4s, while subsequent ones take around .1s, irrespective of query length or relatedness. Out of curiosity, do you know what causes that? Is that golang doing some caching?

I haven't experienced this. Can you provide an example of the command to test on my machine? (I assume it is a shell script?) Maybe we could open a new issue and search why that is happening.